const footerUrlConstants = {
  ABOUT_PAGE: '/about',
  PRIVACY_PAGE: '/privacy',
  TERMS_PAGE: '/terms',
  COPYRIGHT_PAGE: '/copyright',
  SUBSCRIPTION_TERMS_PAGE: '/subscription-terms',
  CONTEST_TERMS_PAGE: '/contest-terms',
  UGC_TERMS_PAGE: '/ugc-terms-of-use',
  CAREERS_PAGE: '/careers',
  PRESS_PAGE: '/press',
  EVENTS_PAGE: '/events',
  BLOG_HOME_PAGE: '/blog/home',
  IPSY_OS: 'http://ipsyos.com',
  HELP_DESK: 'http://help.ipsy.com',
  IPSY_CARE: 'https://ipsy.kustomer.help/contact/contact-us-rkhrO3Hr',
  IPSY_CARE_TWITTER: 'http://twitter.com/ipsycare',
  COMMUNITY_PAGE: '/community',
  IPSY_FACEBOOK_PAGE: 'http://www.facebook.com/ipsy',
  IPSY_TWITTER_PAGE: 'http://www.twitter.com/ipsy',
  IPSY_PINTEREST_PAGE: 'http://www.pinterest.com/ipsy',
  IPSY_YOUTUBE_PAGE: 'http://www.youtube.com/ipsy',
  IPSY_INSTAGRAM_PAGE: 'http://www.instagram.com/ipsy',
  IPSY_GOOGLE_PLUS_PAGE: 'http://plus.google.com/+ipsydotcom',
  IPSY_SNAPCHAT_PAGE: 'https://www.snapchat.com/add/ipsyofficial',
  SHOP_HOME: '/shop/home',
  SHOP_IPSY_OFFERS: '/shop/collections/offers',
  SITEMAP_PAGE: '/sitemap',
  SUPPLY_CHAIN_TRANSPARENCY: '/supplychain',
  COPYRIGHT: '/copyright',
  GLAM_BAG: '/glambag',
  GLAM_BAG_PLUS: '/plus',
  GLAM_BAG_ULTIMATE: '/ultimate',
};

export default footerUrlConstants;
